# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
dist: xenial

python:
  - 3.7
  - 3.6
  - 3.5

install:
  - make ensure-pip-ci
  - make dev-ci

script:
  - make check
  - make requirements
  - make test

# after_success:
#   coveralls

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  user: stibbons
  distributions: sdist bdist_wheel
  password:
    secure: >
      rUTQIwNzTPoWX552eYvERnRZ/LCrU7aiZ53Rt6hNNpv+IQFnaEsBo/gtIikRYg2yRIm8D86Pqg
      uNDCF7UgxbHwFQgmrAU63yGP4DsThvA2lGM55FKA7rojcln84tA+eqhTRqvZFAMKmCfigOdASR
      PsMN6J2wk1NwEbKG4pY1mNPmbblkeKDUHTzEledj3akb4O50oh3HMll3IG8TSWdSLn2p560Tzs
      9yA9y18Qmg8nwGFIllHxO3z95fA9azBPtVCNfmI4bHnvoL6/7iiCYy8VKt1VgmSM8SedtwB5E9
      KckVLaVYWZ0F061nTv/lf404YiVdIjEgZW4pO7aG6FqQDXnMgeVVtSOS7uI7LygUyu0kgWHwHr
      kLXS6g/fO2D3+38TnryjdHo3B+XIp7aItsVUKyC2ppllLHHWdFYhL/EoHtgxtNB8kVo58kal4I
      1ZreQO+7sEu/yzzBY+/bblz62ZOsrfJOmnhveH02vvwMwKW5NOTJHhsgh9RjO2FU6U1yeRZ2vF
      tmr19d9qPNmBj5iAxlHqYLq6B++SWmZiZLxNbMeTf5K0jqZxeuA1+m0pPfZQfYF/fsIXnKkC/5
      zTFX/FEdA1Ubj8RYa6BUkeNJ0ZiJJEtFNgvs6sctl75xeeT+wcF2X4E/pvmANanxWZ+2rSq9sr
      V3Wd2h0tuKxI+xD3U=
  on:
    tags: true
    repo: gsemet/pipenv-to-requirements
    branch: master
